env:  
    node: true  
extends:
  - plugin:@typescript-eslint/recommended  
  - prettier/@typescript-eslint  
  - plugin:prettier/recommended 
parser: '@typescript-eslint/parser'  
parserOptions:  
    ecmaVersion: 9
    project: ./tsconfig.json  
plugins:  
- '@typescript-eslint'
rules:
  "prettier:prettier":"on"


// {
//     "extends": [
//         "airbnb", 
//         "prettier", 
//         "plugin:node/recommended", 
//         "typescript",
//         "prettier/@typescript-eslint",
//         "plugin:@typescript-eslint/recommended"
//     ],
//     "plugins": ["prettier"],
//     "parser": "@typescript-eslint/parser",
//     "parserOptions": {
//         "ecmaVersion": 2018,
//         "sourceType": "module"
//     },
//     "rules":{

//     }
// }
